import { BalanceFeedRow } from './types';

export const DEMO_ROWS: BalanceFeedRow[] = [
  {
    action: 'MERGE',
    balanceCode: 'XX CP HWB Program Report Hours Worked',
    effectiveStartDate: '1951/01/01',
    legislativeDataGroupName: 'US Legislative Data Group',
    elementCode: 'XX Bereavement Pay Earnings Results',
    inputValueCode: 'Hours Calculated',
    addSubtractHuman: 'Add',
  },
  {
    action: 'MERGE',
    balanceCode: 'XX CP HWB Program Report Hours Worked',
    effectiveStartDate: '1951/01/01',
    legislativeDataGroupName: 'US Legislative Data Group',
    elementCode: 'XX Birthday Pay Earnings Results',
    inputValueCode: 'Hours Calculated',
    addSubtractHuman: 'Add',
  },
  {
    action: 'MERGE',
    balanceCode: 'XX CP HWB Program Report Hours Worked',
    effectiveStartDate: '1951/01/01',
    legislativeDataGroupName: 'US Legislative Data Group',
    elementCode: 'XX Holiday Overtime Earnings Results',
    inputValueCode: 'Hours Calculated',
    addSubtractHuman: 'Add',
  },
  {
    action: 'MERGE',
    balanceCode: 'XX CP HWB Program Report Hours Worked',
    effectiveStartDate: '1951/01/01',
    legislativeDataGroupName: 'US Legislative Data Group',
    elementCode: 'XX Overtime Pay Earnings Results',
    inputValueCode: 'Hours Calculated',
    addSubtractHuman: 'Subtract',
  },
  {
    action: 'MERGE',
    balanceCode: 'XX CP HWB Program Report Earnings',
    effectiveStartDate: '1951/01/01',
    legislativeDataGroupName: 'US Legislative Data Group',
    elementCode: 'XX Fire Acting Captain Earnings Results',
    inputValueCode: 'Earnings Calculated',
    addSubtractHuman: 'Add',
  },
  {
    action: 'MERGE',
    balanceCode: 'XX CP HWB Program Report Earnings',
    effectiveStartDate: '1951/01/01',
    legislativeDataGroupName: 'US Legislative Data Group',
    elementCode: 'XX Holiday Pay Earnings Results',
    inputValueCode: 'Earnings Calculated',
    addSubtractHuman: 'Add',
  },
  {
    action: 'MERGE',
    balanceCode: 'XX CP HWB Program Report Hours Worked',
    effectiveStartDate: '1951/01/01',
    legislativeDataGroupName: 'US Legislative Data Group',
    elementCode: 'XX Jury Duty Pay Earnings Results',
    inputValueCode: 'Hours Calculated',
    addSubtractHuman: 'Add',
  },
];
