import {
  ElementEligibilityRow,
  CostInfoRow,
  CostAllocationRow,
  CostAllocationAccountRow,
} from './types';

// ===== FILE 1: PayrollElementDefinition.dat (ElementEligibility) =====
// Source: MC050 tab 28.01 + HDL sample
// Pattern: 3 rows per base element (Canadian Calculation, base, Result)
export const DEMO_ELIGIBILITY_ROWS: ElementEligibilityRow[] = [
  // --- Call back pay 1_0 ---
  {
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_0 Canadian Calculation',
    elementEligibilityName: 'TL Call back pay 1_0 Canadian Calculation-Hours Cost',
    effectiveStartDate: '1951/01/01',
    payrollStatUnitCode: '',
    legalEmployerCode: '',
    payrollCode: '',
    bargainingUnitCode: '',
    automaticEntryFlag: 'No',
    peopleGroup: '',
    costingLinkFlag: '',
  },
  {
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_0',
    elementEligibilityName: 'TL Call back pay 1_0',
    effectiveStartDate: '1951/01/01',
    payrollStatUnitCode: '',
    legalEmployerCode: '',
    payrollCode: '',
    bargainingUnitCode: '',
    automaticEntryFlag: 'No',
    peopleGroup: '',
    costingLinkFlag: '',
  },
  {
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_0 Result',
    elementEligibilityName: 'TL Call back pay 1_0 Results-Earnings Cost',
    effectiveStartDate: '1951/01/01',
    payrollStatUnitCode: '',
    legalEmployerCode: '',
    payrollCode: '',
    bargainingUnitCode: '',
    automaticEntryFlag: 'No',
    peopleGroup: '',
    costingLinkFlag: '',
  },
  // --- Call back pay 1_5 ---
  {
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_5 Canadian Calculation',
    elementEligibilityName: 'TL Call back pay 1_5 Canadian Calculation-Hours Cost',
    effectiveStartDate: '1951/01/01',
    payrollStatUnitCode: '',
    legalEmployerCode: '',
    payrollCode: '',
    bargainingUnitCode: '',
    automaticEntryFlag: 'No',
    peopleGroup: '',
    costingLinkFlag: '',
  },
  {
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_5',
    elementEligibilityName: 'TL Call back pay 1_5',
    effectiveStartDate: '1951/01/01',
    payrollStatUnitCode: '',
    legalEmployerCode: '',
    payrollCode: '',
    bargainingUnitCode: '',
    automaticEntryFlag: 'No',
    peopleGroup: '',
    costingLinkFlag: '',
  },
  {
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_5 Result',
    elementEligibilityName: 'TL Call back pay 1_5 Results-Earnings Cost',
    effectiveStartDate: '1951/01/01',
    payrollStatUnitCode: '',
    legalEmployerCode: '',
    payrollCode: '',
    bargainingUnitCode: '',
    automaticEntryFlag: 'No',
    peopleGroup: '',
    costingLinkFlag: '',
  },
  // --- Evening premium ---
  {
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Evening premium Canadian Calculation',
    elementEligibilityName: 'TL Evening premium Canadian Calculation-Hours Cost',
    effectiveStartDate: '1951/01/01',
    payrollStatUnitCode: '',
    legalEmployerCode: '',
    payrollCode: '',
    bargainingUnitCode: '',
    automaticEntryFlag: 'No',
    peopleGroup: '',
    costingLinkFlag: '',
  },
  {
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Evening premium',
    elementEligibilityName: 'TL Evening premium',
    effectiveStartDate: '1951/01/01',
    payrollStatUnitCode: '',
    legalEmployerCode: '',
    payrollCode: '',
    bargainingUnitCode: '',
    automaticEntryFlag: 'No',
    peopleGroup: '',
    costingLinkFlag: '',
  },
  {
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Evening premium Result',
    elementEligibilityName: 'TL Evening premium Results-Earnings Cost',
    effectiveStartDate: '1951/01/01',
    payrollStatUnitCode: '',
    legalEmployerCode: '',
    payrollCode: '',
    bargainingUnitCode: '',
    automaticEntryFlag: 'No',
    peopleGroup: '',
    costingLinkFlag: '',
  },
];

// ===== FILE 2: CostInfoV3.dat =====
// Source: HDL sample file
// Pattern: 4 rows per costed element pair (EL + LIV for Canadian Calculation, EL + LIV for Results)
// NOTE: Base element does NOT appear in CostInfo
export const DEMO_COST_INFO_ROWS: CostInfoRow[] = [
  // --- Call back pay 1_0: Canadian Calculation ---
  {
    costableType: 'C',
    distributionSetName: '',
    costedFlag: 'Y',
    effectiveEndDate: '4712/12/31',
    effectiveStartDate: '1951/01/01',
    sourceType: 'EL',
    transferToGlFlag: 'Y',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_0 Canadian Calculation',
    elementEligibilityName: 'TL Call back pay 1_0 Canadian Calculation-Hours Cost',
    linkInputName: '',
  },
  {
    costableType: 'C',
    distributionSetName: '',
    costedFlag: 'Y',
    effectiveEndDate: '4712/12/31',
    effectiveStartDate: '1951/01/01',
    sourceType: 'LIV',
    transferToGlFlag: 'Y',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_0 Canadian Calculation',
    elementEligibilityName: 'TL Call back pay 1_0 Canadian Calculation-Hours Cost',
    linkInputName: 'Hours',
  },
  // --- Call back pay 1_0: Results ---
  // NOTE: ElementCode uses "Results" (plural) in costing files
  {
    costableType: 'C',
    distributionSetName: '',
    costedFlag: 'Y',
    effectiveEndDate: '4712/12/31',
    effectiveStartDate: '1951/01/01',
    sourceType: 'EL',
    transferToGlFlag: 'Y',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_0 Results',
    elementEligibilityName: 'TL Call back pay 1_0 Results-Earnings Cost',
    linkInputName: '',
  },
  {
    costableType: 'C',
    distributionSetName: '',
    costedFlag: 'Y',
    effectiveEndDate: '4712/12/31',
    effectiveStartDate: '1951/01/01',
    sourceType: 'LIV',
    transferToGlFlag: 'Y',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_0 Results',
    elementEligibilityName: 'TL Call back pay 1_0 Results-Earnings Cost',
    linkInputName: 'Pay Value',
  },
  // --- Call back pay 1_5: Canadian Calculation ---
  {
    costableType: 'C',
    distributionSetName: '',
    costedFlag: 'Y',
    effectiveEndDate: '4712/12/31',
    effectiveStartDate: '1951/01/01',
    sourceType: 'EL',
    transferToGlFlag: 'Y',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_5 Canadian Calculation',
    elementEligibilityName: 'TL Call back pay 1_5 Canadian Calculation-Hours Cost',
    linkInputName: '',
  },
  {
    costableType: 'C',
    distributionSetName: '',
    costedFlag: 'Y',
    effectiveEndDate: '4712/12/31',
    effectiveStartDate: '1951/01/01',
    sourceType: 'LIV',
    transferToGlFlag: 'Y',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_5 Canadian Calculation',
    elementEligibilityName: 'TL Call back pay 1_5 Canadian Calculation-Hours Cost',
    linkInputName: 'Hours',
  },
  // --- Evening premium: Results only (no Canadian Calculation in costing for this element) ---
  {
    costableType: 'C',
    distributionSetName: '',
    costedFlag: 'Y',
    effectiveEndDate: '4712/12/31',
    effectiveStartDate: '1951/01/01',
    sourceType: 'EL',
    transferToGlFlag: 'Y',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Evening premium Results',
    elementEligibilityName: 'TL Evening premium Results-Earnings Cost',
    linkInputName: '',
  },
  {
    costableType: 'C',
    distributionSetName: '',
    costedFlag: 'Y',
    effectiveEndDate: '4712/12/31',
    effectiveStartDate: '1951/01/01',
    sourceType: 'LIV',
    transferToGlFlag: 'Y',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Evening premium Results',
    elementEligibilityName: 'TL Evening premium Results-Earnings Cost',
    linkInputName: 'Pay Value',
  },
];

// ===== FILE 3: CostAllocationV3.dat =====
// Source: HDL sample file
// Pattern: 1 row per costed eligibility (same set as CostInfo, but no EL/LIV split)
export const DEMO_COST_ALLOCATION_ROWS: CostAllocationRow[] = [
  {
    effectiveEndDate: '4712/12/31',
    effectiveStartDate: '1951/01/01',
    sourceType: 'EL',
    elementCode: 'TL Call back pay 1_0 Canadian Calculation',
    elementEligibilityName: 'TL Call back pay 1_0 Canadian Calculation-Hours Cost',
    legislativeDataGroupName: 'Acme CA LDG',
  },
  {
    effectiveEndDate: '4712/12/31',
    effectiveStartDate: '1951/01/01',
    sourceType: 'EL',
    elementCode: 'TL Call back pay 1_0 Results',
    elementEligibilityName: 'TL Call back pay 1_0 Results-Earnings Cost',
    legislativeDataGroupName: 'Acme CA LDG',
  },
  {
    effectiveEndDate: '4712/12/31',
    effectiveStartDate: '1951/01/01',
    sourceType: 'EL',
    elementCode: 'TL Call back pay 1_5 Canadian Calculation',
    elementEligibilityName: 'TL Call back pay 1_5 Canadian Calculation-Hours Cost',
    legislativeDataGroupName: 'Acme CA LDG',
  },
  {
    effectiveEndDate: '4712/12/31',
    effectiveStartDate: '1951/01/01',
    sourceType: 'EL',
    elementCode: 'TL Evening premium Results',
    elementEligibilityName: 'TL Evening premium Results-Earnings Cost',
    legislativeDataGroupName: 'Acme CA LDG',
  },
];

// ===== FILE 4: CostAllocationAccountV3.dat =====
// Source: MC050 tab 28.03 + HDL sample file
// Pattern: 2 rows per costed eligibility (COST account + BAL offset account)
export const DEMO_COST_ALLOCATION_ACCOUNT_ROWS: CostAllocationAccountRow[] = [
  // --- Call back pay 1_0: Canadian Calculation ---
  // COST: Account=920110
  {
    sourceType: 'EL',
    segment1: '',
    segment2: '',
    segment3: '',
    segment4: '920110',
    segment5: '',
    segment6: '',
    sourceSubType: 'COST',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_0 Canadian Calculation',
    elementEligibilityName: 'TL Call back pay 1_0 Canadian Calculation-Hours Cost',
    effectiveDate: '1951/01/01',
    proportion: '1',
    subTypeSequence: '1',
  },
  // BAL: CostCenter=00, Job=00, Account=928997
  {
    sourceType: 'EL',
    segment1: '',
    segment2: '00',
    segment3: '00',
    segment4: '928997',
    segment5: '',
    segment6: '',
    sourceSubType: 'BAL',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_0 Canadian Calculation',
    elementEligibilityName: 'TL Call back pay 1_0 Canadian Calculation-Hours Cost',
    effectiveDate: '1951/01/01',
    proportion: '1',
    subTypeSequence: '1',
  },
  // --- Call back pay 1_0: Results ---
  // COST: CostCenter=00, Account=600310
  {
    sourceType: 'EL',
    segment1: '',
    segment2: '00',
    segment3: '',
    segment4: '600310',
    segment5: '',
    segment6: '',
    sourceSubType: 'COST',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_0 Results',
    elementEligibilityName: 'TL Call back pay 1_0 Results-Earnings Cost',
    effectiveDate: '1951/01/01',
    proportion: '1',
    subTypeSequence: '1',
  },
  // BAL: CostCenter=00, Job=00, Account=102020
  {
    sourceType: 'EL',
    segment1: '',
    segment2: '00',
    segment3: '00',
    segment4: '102020',
    segment5: '',
    segment6: '',
    sourceSubType: 'BAL',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_0 Results',
    elementEligibilityName: 'TL Call back pay 1_0 Results-Earnings Cost',
    effectiveDate: '1951/01/01',
    proportion: '1',
    subTypeSequence: '1',
  },
  // --- Call back pay 1_5: Canadian Calculation ---
  // COST: Account=920130
  {
    sourceType: 'EL',
    segment1: '',
    segment2: '',
    segment3: '',
    segment4: '920130',
    segment5: '',
    segment6: '',
    sourceSubType: 'COST',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_5 Canadian Calculation',
    elementEligibilityName: 'TL Call back pay 1_5 Canadian Calculation-Hours Cost',
    effectiveDate: '1951/01/01',
    proportion: '1',
    subTypeSequence: '1',
  },
  // BAL: CostCenter=00, Job=00, Account=928997
  {
    sourceType: 'EL',
    segment1: '',
    segment2: '00',
    segment3: '00',
    segment4: '928997',
    segment5: '',
    segment6: '',
    sourceSubType: 'BAL',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Call back pay 1_5 Canadian Calculation',
    elementEligibilityName: 'TL Call back pay 1_5 Canadian Calculation-Hours Cost',
    effectiveDate: '1951/01/01',
    proportion: '1',
    subTypeSequence: '1',
  },
  // --- Evening premium: Results ---
  // COST: CostCenter=00, Account=601510
  {
    sourceType: 'EL',
    segment1: '',
    segment2: '00',
    segment3: '',
    segment4: '601510',
    segment5: '',
    segment6: '',
    sourceSubType: 'COST',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Evening premium Results',
    elementEligibilityName: 'TL Evening premium Results-Earnings Cost',
    effectiveDate: '1951/01/01',
    proportion: '1',
    subTypeSequence: '1',
  },
  // BAL: CostCenter=00, Job=00, Account=102020
  {
    sourceType: 'EL',
    segment1: '',
    segment2: '00',
    segment3: '00',
    segment4: '102020',
    segment5: '',
    segment6: '',
    sourceSubType: 'BAL',
    legislativeDataGroupName: 'Acme CA LDG',
    elementCode: 'TL Evening premium Results',
    elementEligibilityName: 'TL Evening premium Results-Earnings Cost',
    effectiveDate: '1951/01/01',
    proportion: '1',
    subTypeSequence: '1',
  },
];
