import { InputValueRow } from './types';

export const DEMO_ROWS: InputValueRow[] = [
  {
    legislativeDataGroupName: 'Chartwell CA LDG',
    elementCode: 'TL Call back pay 1_0 Result',
    inputValueCode: 'CRR Costing Default',
    name: 'CRR Costing Default',
    displaySequence: '90',
    specialPurpose: '',
    uom: 'Character',
    effectiveStartDate: '1951/01/01',
    displayFlag: 'N',
    allowUserEntryFlag: 'N',
    valueRequiredFlag: 'Y',
    createDatabaseItemFlag: 'N',
    defaultValue: '00',
    applyDefaultAtRuntimeFlag: 'Y',
    lookupType: '',
    referenceCode: 'COSTING_Chartwell_Job',
    minimumValue: '',
    maximumValue: '',
    valueSet: '',
    validationFormulaCode: '',
    validationSource: '',
    warningOrError: '',
    rateFormulaCode: '',
  },
  {
    legislativeDataGroupName: 'Chartwell CA LDG',
    elementCode: 'TL Call back pay 1_5 Canadian Calculation',
    inputValueCode: 'Straight',
    name: 'Straight',
    displaySequence: '100',
    specialPurpose: '',
    uom: 'Number',
    effectiveStartDate: '1951/01/01',
    displayFlag: 'Y',
    allowUserEntryFlag: 'N',
    valueRequiredFlag: 'Y',
    createDatabaseItemFlag: 'Y',
    defaultValue: '1',
    applyDefaultAtRuntimeFlag: 'Y',
    lookupType: '',
    referenceCode: '',
    minimumValue: '',
    maximumValue: '',
    valueSet: '',
    validationFormulaCode: '',
    validationSource: '',
    warningOrError: '',
    rateFormulaCode: '',
  },
  {
    legislativeDataGroupName: 'Chartwell CA LDG',
    elementCode: 'TL Call back pay 1_5 Canadian Calculation',
    inputValueCode: 'Premium',
    name: 'Premium',
    displaySequence: '101',
    specialPurpose: '',
    uom: 'Number',
    effectiveStartDate: '1951/01/01',
    displayFlag: 'Y',
    allowUserEntryFlag: 'N',
    valueRequiredFlag: 'Y',
    createDatabaseItemFlag: 'Y',
    defaultValue: '0.5',
    applyDefaultAtRuntimeFlag: 'Y',
    lookupType: '',
    referenceCode: '',
    minimumValue: '',
    maximumValue: '',
    valueSet: '',
    validationFormulaCode: '',
    validationSource: '',
    warningOrError: '',
    rateFormulaCode: '',
  },
];
